# Generated by Django 5.2.8 on 2025-12-02 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypets',
            name='avatar',
            field=models.ImageField(blank=True, default='pet_avatars\\default.jpg', null=True, upload_to='pet_avatars/'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
