# Generated by Django 5.2.8 on 2025-12-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_mypets_avatar_mypets_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypets',
            name='avatar',
            field=models.ImageField(blank=True, default='pet_avatars/default.jpg', null=True, upload_to='pet_avatars/'),
        ),
    ]
