# Generated by Django 5.2.8 on 2025-12-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_mypets_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypets',
            name='avatar',
            field=models.ImageField(blank=True, default='pet_avatars/default.jpg', upload_to='pet_avatars/'),
        ),
    ]
