# Generated by Django 5.2.8 on 2025-12-17 22:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_mypets_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mypets',
            name='bday',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='diet',
            field=models.CharField(blank=True, max_length=255, verbose_name='dietary preferences'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date expired'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='health_issues',
            field=models.TextField(blank=True, verbose_name='known health issues'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='health_rating',
            field=models.IntegerField(default=5, help_text='value 1 to 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='health rating #'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='health_status',
            field=models.CharField(blank=True, max_length=255, verbose_name='health status'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='litter_family',
            field=models.CharField(blank=True, max_length=255, verbose_name='litter or family info'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='pets home location'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='source (shelter, breeder, family tc.)'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='veterinary',
            field=models.CharField(blank=True, max_length=255, verbose_name='veterinary info'),
        ),
        migrations.AddField(
            model_name='mypets',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='weight (#lb)'),
        ),
        migrations.AlterField(
            model_name='mypets',
            name='animal_type',
            field=models.CharField(max_length=100, verbose_name='animal type'),
        ),
        migrations.AlterField(
            model_name='mypets',
            name='avatar',
            field=models.ImageField(blank=True, default='pet_avatars/default.jpg', upload_to='pet_avatars/', verbose_name='pet image'),
        ),
        migrations.AlterField(
            model_name='mypets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='mypets',
            name='description',
            field=models.TextField(blank=True, verbose_name='pet description'),
        ),
        migrations.AlterField(
            model_name='mypets',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='mypets',
            name='name',
            field=models.CharField(max_length=100, verbose_name='pet name'),
        ),
        migrations.AlterField(
            model_name='mypets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='pet owner'),
        ),
    ]
