# Generated by Django 5.2.8 on 2025-12-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_mypets_bday_mypets_color_mypets_diet_mypets_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypets',
            name='notes',
            field=models.TextField(blank=True, verbose_name='additional notes'),
        ),
    ]
