# Generated by Django 5.2.8 on 2025-12-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_mypets_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypets',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unspecified')], default='U', max_length=1, verbose_name='sex'),
        ),
    ]
