# Generated by Django 5.2.8 on 2025-12-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_hint_customuser_modified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='modified_at',
            new_name='last_modified',
        ),
    ]
