# Generated by Django 5.2.8 on 2025-12-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_modified_at_customuser_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_agency_dir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_agency_vol',
            field=models.BooleanField(default=False),
        ),
    ]
