# Generated by Django 5.2.8 on 2025-12-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_is_agency_dir_customuser_is_agency_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_agency_staff',
            field=models.BooleanField(default=False),
        ),
    ]
