# Generated by Django 5.2.8 on 2025-12-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agency',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agency',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
