# Generated by Django 5.2.8 on 2026-01-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adoptee',
            name='agency_pet_name',
            field=models.CharField(max_length=30, verbose_name='Agency Name'),
        ),
    ]
