# Generated by Django 5.2.8 on 2026-01-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptees', '0002_adoptee_id_alter_adoptee_agency_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptee',
            name='agency_pet_name',
            field=models.CharField(max_length=30, verbose_name='Agency Pet Name'),
        ),
        migrations.AlterField(
            model_name='adoptee',
            name='pet_photo',
            field=models.ImageField(blank=True, default='adoptions/default.jpg', upload_to='adoptions/', verbose_name='Pet Photo Image Links'),
        ),
    ]
