# Generated by Django 5.2.8 on 2026-01-26 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptees', '0003_alter_adoptee_agency_pet_name_and_more'),
        ('agencys', '0002_agency_contact_email_agency_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptee',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='agencys.agency', verbose_name='Agency'),
        ),
    ]
