# Generated by Django 5.2.8 on 2025-12-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('shots', 'shots'), ('spay/neuter', 'spay/neuter'), ('diet', 'diet'), ('medication', 'medication'), ('other', 'other')], max_length=100),
        ),
    ]
